-- ================================================
-- TABLO YAPISINA DAIR NOT
-- Yazan: Ali Hamza TEKINBAS
--
-- Projedeki 5 tablonun tamamı (KATEGORILER, URUNLER,
-- MUSTERILER, SIPARISLER, SIPARISDETAY) Onur TOPBAS
-- tarafindan tasarlanip main branch'teki bu dosyada
-- olusturulmustur.
--
-- Ali Hamza'nin Gün 3 katkisi:
--   - SIPARISLER ve SIPARISDETAY tablolarinin
--     sutun yapisi, kisitlayicilari ve FK tanimlari
--     birlikte belirlendi. Tablo tasarim kararlari
--     docs/tablo_tasarimi.md dosyasinda belgelendi.
--
-- Ali Hamza'nin Gün 4 katkisi:
--   - 02_veriler.sql dosyasinda SIPARISLER tablosuna
--     10 adet, SIPARISDETAY tablosuna 12 adet
--     gercekci test verisi eklendi.
--
-- Referans: main branch -> sql/01_tablolar.sql
-- ================================================
